export { default as betsPart } from './betsPart'
export { default as calculatePart } from './calculatePart'
export { default as gamePart } from './gamePart'
export { default as roundsPart } from './roundsPart'
export { default } from './сalculateWin'
